name: docker

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker-build-and-push
      uses: docker/build-push-action@v2
      with:
        tags: ralexstokes/ethereum_consensus_monitor:latest
        push: true
